on: [ push ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm install @angular/cli
        working-directory: frontend
      - run: npx ng build
        working-directory: frontend
      - run: cp -r frontend/dist/frontend/* backend/static
      - run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build . -t kruemmelspalter/betterschuman:${{steps.vars.output.tag}}
      - run: docker push kruemmelspalter/betterschuman:${{steps.vars.output.tag}}

      - run: docker build . -t kruemmelspalter/betterschuman:latest
      - run: docker push kruemmelspalter/betterschuman:latest


